---
name: Fabric
description: Hello! This is an example theme to get you started on making great themes on Format.com.
author: Format
author_url: https://www.format.com
support: This a place for you to help users of this theme and how they can keep in touch.

skins:
- name: Light
  id: light
  path: skin_images/light.jpg
- name: Dark
  id: dark
  path: skin_images/dark.jpg
default_skin: light

using_position:
  right: 30
  bottom: 37

preview_images:
  - path: preview_images/1.jpg

mobile_preview_images:
  - path: preview_images/1-mobile.jpg

filter_attributes:
  - slideshow